# Specify the Docker-Compose version
version: '2.1'

# Define the services/containers to be run
services:
  angular: # Name of the first service
    build: angular-client # Specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forwarding
    volumes:
      # - ./angular-client:/app # this will enable changes made to the angular app reflect in the container

  express: 
    build: express-server
    ports: 
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"

## https://scotch.io/tutorials/create-a-mean-app-with-angular-2-and-docker-compose